juju:
  name: "Juju"
  description: "Software operations are easier with Juju – the open source orchestration engine for software operators. Deploy, integrate, scale and manage your applications' lifecycle at any scale, on any infrastructure with Juju and charms."
  operatingSystem: "Linux, Windows, macOS"
  applicationCategory: "DeveloperApplication"
  url: "https://canonical.com/juju"
lxd:
  name: "LXD"
  description: "Low-touch virtual infrastructure with LXD at any scale. Built on top of Linux containers, LXD offers a unified user experience in managing system containers, virtual machines and clusters."
  operatingSystem: "Linux"
  applicationCategory: "SystemApplication"
  url: "https://canonical.com/lxd"
maas:
  name: "MAAS"
  description: "MAAS (Metal as a Service) automates your data center, turning bare metal servers into an efficient, security maintained, and scalable private cloud."
  operatingSystem: "Linux"
  applicationCategory: "BusinessApplication"
  url: "https://canonical.com/maas"
  pricing:
    standaloneSupport:
      title: "MAAS standalone support pricing"
      billing:
        cadence: "annual"
        unit: "per managed machine"
      tiers:
        - name: "Self-support"
          price: "Free"
          summary: "Free for all machines"
          cta:
            text: "Install MAAS"
            url: "https://canonical.com/maas/docs/how-to-get-maas-up-and-running"
          features:
            - name: "High availability (HA) support"
              included: false
            - name: "Role based access control (RBAC)"
              included: false
            - name: "Knowledge Base"
              included: false
            - name: "Response time - SLA Sev 1"
              included: false
            - name: "Phone and ticket support"
              included: false
        - name: "Essential"
          price: "$30"
          summary: "per year, per managed machine"
          cta:
            text: "Contact us"
            url: "https://canonical.com/maas/contact-us"
          features:
            - name: "High availability (HA) support"
              included: true
            - name: "Role based access control (RBAC)"
              included: true
            - name: "Knowledge Base"
              included: true
            - name: "Response time - SLA Sev 1"
              included: false
            - name: "Phone and ticket support"
              included: false
        - name: "Standard"
          price: "$50"
          summary: "per year, per managed machine"
          cta:
            text: "Contact us"
            url: "https://canonical.com/maas/contact-us"
          features:
            - name: "High availability (HA) support"
              included: true
            - name: "Role based access control (RBAC)"
              included: true
            - name: "Knowledge Base"
              included: true
            - name: "Response time - SLA Sev 1"
              included: true
              value: "4 hours"
            - name: "Phone and ticket support"
              included: true
              value: "Office hours"
        - name: "Advanced"
          price: "$100"
          summary: "per year, per managed machine"
          cta:
            text: "Contact us"
            url: "https://canonical.com/maas/contact-us"
          features:
            - name: "High availability (HA) support"
              included: true
            - name: "Role based access control (RBAC)"
              included: true
            - name: "Knowledge Base"
              included: true
            - name: "Response time - SLA Sev 1"
              included: true
              value: "1 hour"
            - name: "Phone and ticket support"
              included: true
              value: "24 hours a day, everyday"
microk8s:
  name: "MicroK8s"
  description: "High availability Kubernetes with autonomous clusters. MicroK8s is the simplest production-grade conformant K8s for edge and IoT, on Linux, Windows, and macOS."
  operatingSystem: "Linux, Windows, macOS"
  applicationCategory: "DeveloperApplication"
  url: "https://canonical.com/microk8s"
multipass:
  name: "Multipass"
  description: "Multipass is a CLI to launch and manage VMs on Windows, Mac and Linux that simulates a cloud environment with support for cloud-init."
  operatingSystem: "Linux, Windows, macOS"
  applicationCategory: "DeveloperApplication"
  url: "https://canonical.com/multipass"
