juju:
  name: "Juju"
  description: "Software operations are easier with Juju – the open source orchestration engine for software operators. Deploy, integrate, scale and manage your applications' lifecycle at any scale, on any infrastructure with Juju and charms."
  operatingSystem: "Linux, Windows, macOS"
  applicationCategory: "DeveloperApplication"
  url: "https://canonical.com/juju"
lxd:
  name: "LXD"
  description: "Low-touch virtual infrastructure with LXD at any scale. Built on top of Linux containers, LXD offers a unified user experience in managing system containers, virtual machines and clusters."
  operatingSystem: "Linux"
  applicationCategory: "SystemApplication"
  url: "https://canonical.com/lxd"
maas:
  name: "MAAS"
  description: "MAAS (Metal as a Service) automates your data center, turning bare metal servers into an efficient, security maintained, and scalable private cloud."
  operatingSystem: "Linux"
  applicationCategory: "BusinessApplication"
  url: "https://canonical.com/maas"
microk8s:
  name: "MicroK8s"
  description: "High availability Kubernetes with autonomous clusters. MicroK8s is the simplest production-grade conformant K8s for edge and IoT, on Linux, Windows, and macOS."
  operatingSystem: "Linux, Windows, macOS"
  applicationCategory: "DeveloperApplication"
  url: "https://canonical.com/microk8s"
multipass:
  name: "Multipass"
  description: "Multipass is a CLI to launch and manage VMs on Windows, Mac and Linux that simulates a cloud environment with support for cloud-init."
  operatingSystem: "Linux, Windows, macOS"
  applicationCategory: "DeveloperApplication"
  url: "https://canonical.com/multipass"
