import uuid
from pathlib import Path
from github import Github, GithubException
from canonicalwebteam.flask_base.env import get_flask_env


class PRGenerator:
    def __init__(self, repo_name: str):
        # The fine grained token must have following permissions
        # against the target repository:
        # 1. contents: read/write
        # 2. metadata: read
        # 3. pull_requests: read/write
        self.git = Github(get_flask_env("PAGE_GENERATOR_GITHUB_TOKEN"))
        self.repo_name = repo_name
        self.repository = None
        self.new_branch_name = None

    def setup_branch(self, base_branch: str = "main"):
        """Prepares the repository and creates a new feature branch."""
        try:
            self.repository = self.git.get_repo(self.repo_name)
            base_sha = self.repository.get_branch(base_branch).commit.sha
            self.new_branch_name = f"page-gen-{uuid.uuid4().hex[:8]}"

            self.repository.create_git_ref(
                ref=f"refs/heads/{self.new_branch_name}", sha=base_sha
            )
        except GithubException as e:
            print(f"Error initializing PR: {e}")
            raise

    def create_pull_request(self, file_path: str, base_branch: str = "main"):
        """Uploads file and opens the PR."""
        if not self.new_branch_name:
            self.setup_branch(base_branch)

        path_obj = Path(file_path)
        if not path_obj.exists():
            raise FileNotFoundError(f"Source file {file_path} not found.")

        try:
            content = path_obj.read_text()

            # 1. Create the file in the new branch
            self.repository.create_file(
                path=str(file_path),
                message="feat: add auto-generated page",
                content=content,
                branch=self.new_branch_name,
            )

            # 2. Create the Pull Request
            pr = self.repository.create_pull(
                title="Add new page generated by page generator",
                body="This PR was automatically generated.",
                head=self.new_branch_name,
                base=base_branch,
            )

            return pr.html_url

        except GithubException as e:
            print(f"GitHub API Error: {e}")
            return None
