domain: canonical.com

image: prod-comms.ps5.docker-registry.canonical.com/canonical.com

env:
  - name: CANONICAL_CLA_API_URL
    value: https://cla.staging.canonical.com

  - name: SENTRY_DSN
    value: https://aedc7a57f0bc4d22bf7c0b6d63c3e1bb@sentry.is.canonical.com//14

  - name: GREENHOUSE_API_KEY
    secretKeyRef:
      key: greenhouse_api_key
      name: canonical-com

  - name: HARVEST_API_KEY
    secretKeyRef:
      key: harvest_api_key
      name: canonical-com

  - name: APPLICATION_CRYPTO_SECRET_KEY
    secretKeyRef:
      key: application-crypto-key
      name: greenhouse-credentials

  - name: SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

  - name: SMTP_SENDER_ADDRESS
    value: careers@canonical.com

  - name: SMTP_SERVER
    secretKeyRef:
      key: server
      name: smtp-credentials-careers

  - name: SMTP_USER
    secretKeyRef:
      key: user
      name: smtp-credentials-careers

  - name: SMTP_PASS
    secretKeyRef:
      key: password
      name: smtp-credentials-careers

  - name: DIRECTORY_API_TOKEN
    secretKeyRef:
      key: token
      name: directory-api

  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: ubuntu-api-key
      name: discourse-api

  - name: DISCOURSE_API_USERNAME
    secretKeyRef:
      key: ubuntu-api-username
      name: discourse-api

  - name: CHARMHUB_DISCOURSE_API_KEY
    secretKeyRef:
      key: charmhub-api-key
      name: discourse-api

  - name: CHARMHUB_DISCOURSE_API_USERNAME
    secretKeyRef:
      key: charmhub-api-username
      name: discourse-api

  - name: MAAS_DISCOURSE_API_KEY
    secretKeyRef:
      key: maas-api-key
      name: discourse-api

  - name: MAAS_DISCOURSE_API_USERNAME
    secretKeyRef:
      key: maas-api-username
      name: discourse-api

  - name: SERVICE_ACCOUNT_EMAIL
    secretKeyRef:
      key: scheduler_account_email
      name: greenhouse-credentials

  - name: SERVICE_ACCOUNT_PRIVATE_KEY
    secretKeyRef:
      key: scheduler_account_private_key
      name: greenhouse-credentials

  - name: RECAPTCHA_ENABLED
    value: "true"

  - name: RECAPTCHA_SITE_KEY
    value: "6LcOo40qAAAAAKN6mBrlbr-npUv1zyWSxJknU959"

  - name: RECAPTCHA_PROJECT_ID
    value: "site-canonical-c-1732626873862"

  - name: RECAPTCHA_API_KEY
    secretKeyRef:
      key: api-key
      name: canonical-com-gcloud

  - name: RECAPTCHA_SCORE_THRESHOLD
    value: "0.5"

  - name: SITEMAP_SECRET
    secretKeyRef:
      key: secret
      name: sitemaps

extraHosts:
  - domain: blog.canonical.com
  - domain: design.canonical.com
  - domain: partners.canonical.com

# Overrides for production
production:
  replicas: 5
  routes:
    - paths: [/blog]
      name: canonical-com-blog
      app_name: canonical.com-blog
      image: prod-comms.ps5.docker-registry.canonical.com/canonical.com
      replicas: 3
      memoryLimit: 256Mi
      env:
        - name: CANONICAL_CLA_API_URL
          value: https://cla.canonical.com

        - name: SEARCH_API_KEY
          secretKeyRef:
            key: google-custom-search-key
            name: google-api

        - name: APPLICATION_CRYPTO_SECRET_KEY
          secretKeyRef:
            key: application-crypto-key
            name: greenhouse-credentials

        - name: SENTRY_DSN
          value: https://aedc7a57f0bc4d22bf7c0b6d63c3e1bb@sentry.is.canonical.com//14

        - name: SERVICE_ACCOUNT_EMAIL
          secretKeyRef:
            key: scheduler_account_email
            name: greenhouse-credentials

        - name: SERVICE_ACCOUNT_PRIVATE_KEY
          secretKeyRef:
            key: scheduler_account_private_key
            name: greenhouse-credentials

  nginxConfigurationSnippet: |
    if ($host = 'blog.canonical.com' ) {
      rewrite ^ https://canonical.com/blog$request_uri? permanent;
    }
    if ($host = 'design.canonical.com' ) {
      rewrite ^ https://ubuntu.com/blog/topics/design permanent;
    }
    if ($host = 'partners.canonical.com' ) {
      rewrite ^ https://canonical.com permanent;
    }
    if ($host != 'canonical.com' ) {
      rewrite ^ https://canonical.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  routes:
    - paths: [/blog]
      name: canonical-com-blog
      app_name: canonical.com-blog
      image: prod-comms.ps5.docker-registry.canonical.com/canonical.com
      replicas: 3
      memoryLimit: 256Mi
      env:
        - name: SEARCH_API_KEY
          secretKeyRef:
            key: google-custom-search-key
            name: google-api

        - name: APPLICATION_CRYPTO_SECRET_KEY
          secretKeyRef:
            key: application-crypto-key
            name: greenhouse-credentials

        - name: SENTRY_DSN
          value: https://aedc7a57f0bc4d22bf7c0b6d63c3e1bb@sentry.is.canonical.com//14

        - name: DIRECTORY_API_TOKEN
          secretKeyRef:
            key: token
            name: directory-api

        - name: FLASK_DEBUG
          value: True

        - name: GREENHOUSE_DEBUG
          value: "true"

        - name: SERVICE_ACCOUNT_EMAIL
          secretKeyRef:
            key: scheduler_account_email
            name: greenhouse-credentials

        - name: SERVICE_ACCOUNT_PRIVATE_KEY
          secretKeyRef:
            key: scheduler_account_private_key
            name: greenhouse-credentials

  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    if ($host != 'staging.canonical.com' ) {
      rewrite ^ https://staging.canonical.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

demo:
  env:
    - name: DIRECTORY_API_TOKEN
      secretKeyRef:
        key: token
        name: directory-api

    - name: FLASK_DEBUG
      value: True

    - name: GREENHOUSE_DEBUG
      value: "true"
