REGION_COUNTRIES = {
    "emea": [
        "Afghanistan",
        "Åland Islands",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Armenia",
        "Austria",
        "Azerbaijan",
        "Bahrain",
        "Belarus",
        "Belgium",
        "Benin",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cabo Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo (Democratic Republic of the)",
        "Congo",
        "Côte d’Ivoire",
        "Croatia",
        "Cyprus",
        "Czechia",
        "Denmark",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands",
        "Faroe Islands",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Vatican City",
        "Hungary",
        "Iceland",
        "Iran",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kuwait",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "North Macedonia",
        "Madagascar",
        "Malawi",
        "Mali",
        "Malta",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Netherlands",
        "Niger",
        "Nigeria",
        "Norway",
        "Oman",
        "Palestine",
        "Poland",
        "Portugal",
        "Qatar",
        "Réunion",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Helena",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Slovakia",
        "Slovenia",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "South Sudan",
        "Spain",
        "Sudan",
        "Svalbard",
        "Eswatini",
        "Sweden",
        "Switzerland",
        "Syria",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Turkey",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe",
    ],
    "apac": [
        "American Samoa",
        "Antarctica",
        "Australia",
        "Bangladesh",
        "Bhutan",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Cambodia",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Cook Islands",
        "Fiji",
        "French Polynesia",
        "French Southern Territories",
        "Guam",
        "Heard Island and McDonald Islands",
        "Hong Kong",
        "India",
        "Indonesia",
        "Japan",
        "Kiribati",
        "Korea (Democratic People’s Republic of)",
        "Korea (Republic of)",
        "Kyrgyzstan",
        "Laos",
        "Macao",
        "Malaysia",
        "Maldives",
        "Marshall Islands",
        "Micronesia",
        "Mongolia",
        "Myanmar",
        "Nauru",
        "Nepal",
        "New Caledonia",
        "New Zealand",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Pakistan",
        "Palau",
        "Papua New Guinea",
        "Philippines",
        "Pitcairn",
        "Samoa",
        "Singapore",
        "Solomon Islands",
        "Sri Lanka",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Timor-Leste",
        "Tokelau",
        "Tonga",
        "Turkmenistan",
        "Tuvalu",
        "United States Minor Outlying Islands",
        "Uzbekistan",
        "Vanuatu",
        "Viet Nam",
        "Wallis and Futuna",
    ],
    "amer": [
        "Anguilla",
        "Antigua and Barbuda",
        "Argentina",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bermuda",
        "Bolivia (Plurinational State of)",
        "Bonaire, Sint Eustatius and Saba",
        "Brazil",
        "Canada",
        "Cayman Islands",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Curaçao",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "El Salvador",
        "French Guiana",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Guyana",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Martinique",
        "Mexico",
        "Montserrat",
        "Nicaragua",
        "Panama",
        "Paraguay",
        "Peru",
        "Puerto Rico",
        "Saint Barthélemy",
        "Saint Kitts And Nevis",
        "Saint Lucia",
        "Saint Martin",
        "Saint Pierre and Miquelon",
        "Saint Vincent and The Grenadines",
        "Sint Maarten (Dutch part)",
        "Suriname",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "United States of America",
        "Uruguay",
        "Venezuela",
        "Virgin Islands (British)",
        "Virgin Islands (U.S.)",
    ],
}
