name: llms.txt generation for canonical.com
on:
  push:
    branches:
      - main
    paths:
      - "templates/**"
      - "llms.yaml"

jobs:
  generate-llms:
    if: github.repository == 'canonical/canonical.com'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Regenerate llms.txt
        run: |
          curl --fail-with-body -X POST "https://canonical.com/llms.txt" \
          -H "Authorization: Bearer ${{ secrets.SITEMAP_SECRET }}"

      - name: Regenerate llms-full.txt
        run: |
          curl --fail-with-body --max-time 300 -X POST \
          "https://canonical.com/llms-full.txt" \
          -H "Authorization: Bearer ${{ secrets.SITEMAP_SECRET }}"

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=web-alerts
